---
# vars file for mysql-role

mariadb_install: ['mariadb-server','python-PyMySQL']
mariadb_socket: /database-data/mysql/mysql.sock
mariadb_datadir: /database-data/mysql
#mariadb_pid_file: /var/run/mariadb/mariadb.pid
