- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Create cert DIR
  ansible.builtin.file:
    path: /certs
    state: directory
    owner: root 
    group: root
    mode: '0755'

- name: Copy certs
  ansible.builtin.copy:
    src: "bastion/"
    dest: "/certs/"
    owner: root
    group: root
    mode: '0644'

#- name: Generate private key
#  community.crypto.openssl_privatekey:
#    path: /certs/nginx.key
#    type: RSA
#    size: 4096
#    state: present
#    mode: '0600'

#- name: Generate cert
#  community.crypto.x509_certificate:
#    path: /certs/nginx.crt
#    privatekey_path: /certs/nginx.key
#    provider: selfsigned
#    selfsigned_subject:
#      common_name: "{{ansible_host}}"
#    selfsigned_not_after: 365d
#    mode: '0644'

- name: Create config file
  ansible.builtin.template:
    src: bastion-rproxy.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart Nginx

- name: Start and Enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true


