- name: Install Mariadb
  ansible.builtin.dnf:
    name: "{{mariadb_install}}" 
    state: present

- name: Create mysql dir
  ansible.builtin.file:
    state: directory
    path: /database-data/mysql
    owner: mysql
    group: mysql
    mode: '2750'

- name: Call Firewalld
  ansible.builtin.import_role:
    name: firewalld-role
    tasks_from: mariadb.yaml

- name: Call SeLinux
  ansible.builtin.import_role:
    name: selinux-role
    tasks_from: mariadb.yaml

- name: Create Config File
  ansible.builtin.template:
    src: server.cnf.j2
    dest: /etc/my.cnf.d/server.cnf
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart Mariadb


- name: Start and Enable Mariadb
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Configure root user
  community.mysql.mysql_user:
    host_all: true
    name: root
    password: "{{db_password}}"
    state: present
    update_password: always
    login_unix_socket: "{{mariadb_socket}}"
  ignore_errors: true

- name: Import deploy_database.yaml
  ansible.builtin.import_tasks: deploy_database.yaml
