- name: Zone Exsists
  ansible.builtin.stat:
    path: /etc/firewalld/zones/database-zone.xml
  register: zone_stat
    
- name: Create new zone
  ansible.builtin.template:
    src: database-zone.xml.j2
    dest: /etc/firewalld/zones/database-zone.xml
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload firewalld
  when: zone_stat.stat.exists == false

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Get default zone
  ansible.builtin.command: 'firewall-cmd --get-default-zone'
  register: default_zone

- name: Set default zone
  ansible.builtin.command: 'firewall-cmd --set-default-zone={{database_zone}}'
  when: "database_zone not in default_zone.stdout"

