- name: Reload firewalld
  ansible.builtin.command: 'firewall-cmd --reload'
  when: ansible_distribution == 'RedHat'

- name: Set default zone
  ansible.builtin.command: 'firewall-cmd --set-default-zone={{webserver_zone}}'
  when: "'webserver' in group_names"

- name: Set default zone
  ansible.builtin.command: 'firewall-cmd --set-default-zone={{database_zone}}'
  when: "'database' in group_names"

- name: Reload nftables
  ansible.builtin.command: 'nft -f /etc/nftables.conf'
  when: "'bastion' in group_names"
