- name: Create sshd service file
  ansible.builtin.template:
    src: sshd.xml.j2
    dest: '/etc/firewalld/services/sshd.xml'
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload firewalld

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add custom sshd service
  ansible.builtin.firewalld:
    service: sshd
    immediate: true
    permanent: true
    state: enabled

- name: Remove ssh service
  ansible.builtin.firewalld:
    service: ssh
    immediate: true
    permanent: true
    state: disabled

