- name: Main file
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars/main.yaml
  roles:
    - role: general_settings-role
    - role: firewalld-role
    - role: chrony-role
    - role: storage-role
    - role: httpd-role 
    - role: nginx-role
    - role: suricata-role
    - role: fail2ban-role
    - role: mariadb-role
    - role: cron-role
    - role: sysctl-role
    - role: apparmor-role
    - role: AIDE-role
