- name: Main file
  hosts: all
  gather_facts: true
  become: true
#  vars:
#    https_port: 443
  vars_files:
    - vars/main.yaml
  roles:
    - role: general_settings-role
    - role: firewalld-role
    - role: chrony-role
    - role: storage-role 
    - role: nginx-role
    - role: suricata-role
    - role: fail2ban-role
    - role: mariadb-role
    - role: cron-role
    - role: sysctl-role
    - role: AIDE-role
